// Automatically generated by chapter11.ToStringAnnotationProcessor
package chapter11;
public class ToStrings {
    public static String toString(chapter11.Point obj) {
        var result = new StringBuilder();
        result.append("[");
        result.append(toString(obj.x()));
        result.append(",");
        result.append(toString(obj.y()));
        result.append(",");
        result.append(toString(obj.x()));
        result.append(",");
        result.append(toString(obj.y()));
        result.append("]");
        return result.toString();
    }
    public static String toString(chapter11.Rectangle obj) {
        var result = new StringBuilder();
        result.append("chapter11.Rectangle");
        result.append("[");
        result.append(toString(obj.topLeft()));
        result.append(",");
        result.append("length=");
        result.append(toString(obj.length()));
        result.append(",");
        result.append("width=");
        result.append(toString(obj.width()));
        result.append(",");
        result.append(toString(obj.topLeft()));
        result.append(",");
        result.append("length=");
        result.append(toString(obj.length()));
        result.append(",");
        result.append("width=");
        result.append(toString(obj.width()));
        result.append("]");
        return result.toString();
    }
    public static String toString(Object obj) {
        return java.util.Objects.toString(obj);
    }
}
